# Generated by Django 4.2 on 2023-05-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserView',
            new_name='UserModel',
        ),
    ]
